### ISSUE TITLE
Emitting the "toggle" event

### ISSUE THREAD

**Issue by nesben** [imfaber/vue-tasty-burgers#10]
First, great plugin! I love the animations and the ease when it comes to installing it!

But I'd like to call the toggle event myself. This is because I'm trying to make a click on a menu item close the menu while also navigating to the page (using nuxt-link).

I can easily close the menu I've created, but I can't seem to emit the toggle event...

What can I do?

**Comment by dazuku** [comment]
Hi @Aeka123, this feature is working since version 1.1.7. You only need to change the value of the variable you are sending to `active` prop.

I have something like this:
```
<tasty-burger-button type="elastic"
  size="m"
  color="#10C64E"
  active-color="#10C64E"
  :active="showMenu"
  @toggle="onBurgerToggled"
/>
```

And `showMenu` is a computed variable which is retrieving the value from the state.

```
...
computed: {
  showMenu() {
    return this.$store.state.header.isOpen;
  },
},
...
```

but you can also set a variable inside data and set to false/true whenever you need to emit the close/open action

**Comment by imfaber** [comment]
Hi @Aeka123 

As @dazuku said you can control the button status with the `active` prop.
Let if you have problems using it
